
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.cast_app.replicaCount }}
  selector:
    matchLabels:
      app: cast-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cast-app
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 cast-db-service 5432; do sleep 5; done']
      containers:
        - args:
            - uvicorn
            - app.main:app
            - --reload
            - --host
            - 0.0.0.0
            - --port
            - "8000"
          env:
            - name: DATABASE_URI
              value: {{ .Values.cast_app.databaseURI }}
          image: f3lin/cast-api:latest
          name: cast-app
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always