apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.cast_app.port }} 
      targetPort: 8000 
      nodePort: {{ .Values.cast_app.nodePort }} 
  selector:
    app: cast-app