apiVersion: v1
kind: Service
metadata:
  name: movie-db-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: movie-db
  ports:
    - protocol: TCP
      port: 5432


---

apiVersion: v1
kind: Service
metadata:
  name: cast-db-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: cast-db
  ports:
    - protocol: TCP
      port: 5432