apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: "{{ .Values.image.repository }}/{{ .Values.castService.image }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.castService.port }}
          env:
            - name: DATABASE_URI
              value:  postgresql://cast_db_{{ .Release.Namespace }}:cast_db_password@cast_db.{{ .Release.Namespace }}/cast_db_{{ .Release.Namespace }}

