apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.movie_app.port }}
      targetPort: 8000
      nodePort: {{ .Values.movie_app.nodePort }}
  selector:
    app: movie-app