
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.movie_app.replicaCount }}
  selector:
    matchLabels:
      app: movie-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: movie-app
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 movie-db-service 5432; do sleep 5; done']
      containers:
        - args:
            - uvicorn
            - app.main:app
            - --reload
            - --host
            - 0.0.0.0
            - --port
            - "8000"
          env:
            - name: CAST_SERVICE_HOST_URL
              value: {{ .Values.movie_app.castServiceHostURL }}
            - name: DATABASE_URI
              value: {{ .Values.movie_app.databaseURI }}
          image: {{ .Values.image.movie }}:{{ .Values.image.tag }}
          name: movie-app
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always