# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
#   namespace: dev
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:latest
#         ports:
#         - containerPort: 8080
#         volumeMounts:
#         - name: nginx-config-volume
#           mountPath: /etc/nginx/conf.d/default.conf
#           subPath: nginx_config.conf
#       volumes:
#       - name: nginx-config-volume
#         configMap:
#           name: nginx-config
