apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-movie
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.movie_app.pvc.storage }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-cast
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.cast_app.pvc.storage }}